DRUG_FORMS = [
    ("tablet", "Tablet"),
    ("capsule", "Capsule"),
    ("syrup", "Syrup"),
    ("injection", "Injection"),
    ("ointment", "Ointment"),
    ("cream", "Cream"),
    ("gel", "Gel"),
    ("lotion", "Lotion"),
    ("solution", "Solution"),
    ("suspension", "Suspension"),
    ("emulsion", "Emulsion"),
    ("drops", "Drops (Eye/Ear/Nasal)"),
    ("inhaler", "Inhaler"),
    ("spray", "Spray"),
    ("powder", "Powder"),
    ("granules", "Granules"),
    ("suppository", "Suppository"),
    ("patch", "Transdermal Patch"),
    ("lozenge", "Lozenge"),
    ("chewable", "Chewable Tablet"),
    ("effervescent", "Effervescent Tablet"),
    ("inhalation", "Inhalation Solution"),
    ("nebule", "Nebule"),
    ("ampoule", "Ampoule"),
    ("vial", "Vial"),
    ("prefilled_syringe", "Prefilled Syringe"),
    ("implant", "Implant"),
    ("paste", "Paste"),
    ("foam", "Foam"),
    ("shampoo", "Shampoo"),
    ("enema", "Enema"),
    ("irrigation", "Irrigation Solution"),
    ("inhalation_powder", "Inhalation Powder"),
    ("film", "Oral Film"),
    ("gargle", "Gargle/Mouthwash"),
    ("liniment", "Liniment"),
    ("pessary", "Pessary"),
    ("other", "Other"),
]

DRUG_UNITS = [
    ("mg", "mg"),
    ("g", "g"),
    ("mcg", "mcg (microgram)"),
    ("kg", "kg"),
    ("ml", "ml"),
    ("l", "L (liter)"),
    ("tablet", "Tablet"),
    ("capsule", "Capsule"),
    ("sachet", "Sachet"),
    ("ampoule", "Ampoule"),
    ("vial", "Vial"),
    ("drop", "Drop"),
    ("puff", "Puff"),
    ("patch", "Patch"),
    ("suppository", "Suppository"),
    ("application", "Application"),
    ("unit", "Unit"),
    ("iu", "IU (International Unit)"),
    ("meq", "mEq (milliequivalent)"),
    ("mmol", "mmol (millimole)"),
    ("percent", "% (percent)"),
    ("spray", "Spray"),
    ("piece", "Piece"),
    ("scoop", "Scoop"),
    ("teaspoon", "Teaspoon"),
    ("tablespoon", "Tablespoon"),
    ("ounce", "Ounce (oz)"),
    ("pound", "Pound (lb)"),
    ("inch", "Inch"),
    ("cm", "cm"),
    ("dose", "Dose"),
    ("pack", "Pack"),
    ("cartridge", "Cartridge"),
    ("pen", "Pen"),
    ("nebule", "Nebule"),
    ("bag", "Bag"),
    ("bottle", "Bottle"),
    ("tube", "Tube"),
    ("jar", "Jar"),
    ("canister", "Canister"),
]
ROUTE_SELECTION = [
    ("oral", "Oral"),
    ("buccal", "Buccal"),
    ("sublingual", "Sublingual"),
    ("topical", "Topical"),
    ("transdermal", "Transdermal"),
    ("inhalation", "Inhalation"),
    ("nasal", "Nasal"),
    ("ocular", "Ocular (Eye)"),
    ("otic", "Otic (Ear)"),
    ("injection_iv", "Intravenous (IV)"),
    ("injection_im", "Intramuscular (IM)"),
    ("injection_sc", "Subcutaneous (SC)"),
    ("injection_id", "Intradermal (ID)"),
    ("injection_ia", "Intra-arterial"),
    ("injection_it", "Intrathecal"),
    ("injection_epidural", "Epidural"),
    ("rectal", "Rectal"),
    ("vaginal", "Vaginal"),
    ("urethral", "Urethral"),
    ("intraosseous", "Intraosseous"),
    ("intraperitoneal", "Intraperitoneal"),
    ("intravesical", "Intravesical (Bladder)"),
    ("intravitreal", "Intravitreal (Eye)"),
    ("nebulization", "Nebulization"),
    ("enteral", "Enteral (Tube)"),
    ("intracardiac", "Intracardiac"),
    ("intracranial", "Intracranial"),
    ("intralesional", "Intralesional"),
    ("intraarticular", "Intra-articular (Joint)"),
    ("intracavernosal", "Intracavernosal"),
    ("subcutaneous_implant", "Subcutaneous Implant"),
    ("other", "Other"),
]
FREQUENCY_PERIOD_SELECTION = [
    ('day', 'per Day'),
    ('week', 'per Week'),
    ('hour', 'per Hour'),
    ('as_required', 'As Required (PRN)'),
    ('stat', 'Stat (Once Immediately)'),
    ('other', 'Other'),
]