services:
  fastapi:
    build:
      context: ./backend-fastapi
      dockerfile: Dockerfile
    container_name: fastapi
    ports:
      - "8001:8001"
    env_file:
      - /etc/umcapi.env
    environment:
      REDIS_URL: redis://redis:6379/0
    depends_on:
      - redis
    restart: unless-stopped
    networks:
      - umc-network

  redis:
    image: redis:alpine
    container_name: redis
    restart: unless-stopped
    networks:
      - umc-network

networks:
  umc-network:
    external: true
