# -*- coding: utf-8 -*-
{
    'name': "EMR Configuration Module",
    'summary': "",
    'description': """""",
    'author': "Sarah Unokerieghan",
    'category': 'Configuration',
    'version': '0.1',
    'depends': ['base', 'web','mail', 'base_setup', 'web_tree_many2one_clickable'],
    'data': [
        'security/ir.model.access.csv',
        'security/user_groups.xml',
        # 'data/location_data.xml',
        'data/location_sequence.xml',
        'views/login.xml',
        'views/locations.xml',
        'views/faculties.xml',
        'views/departments.xml',
        'views/medical_conditions.xml',
        'views/medical_allergen.xml',
        'views/medical_reactions.xml',
        'views/medical_immunization.xml',
        'views/provider_specialty.xml',
        'views/emr_provider.xml',
        'views/medical_service.xml',
        'views/emr_encounter.xml',
        'views/menu.xml',
    ],
    'images': ['static/description/icon.png'],
    'demo': [],
    'auto_install': False,
    'application': True,
}

